#!/usr/bin/with-contenv sh

START_NGINX=${START_NGINX:-NO}
if [ "$START_NGINX" = "YES" ]; then
    rm /etc/services.d/nginx/down
fi

START_CRON=${START_CRON:-NO}
if [ "$START_CRON" = "YES" ]; then
    rm /etc/services.d/cron/down
fi

START_PHP_FPM=${START_PHP_FPM:-NO}
if [ "$START_PHP_FPM" = "YES" ]; then
    rm /etc/services.d/php-fpm/down
fi

START_SSH=${START_SSH:-NO}
if [ "$START_SSH" = "YES" ]; then
    rm /etc/services.d/ssh/down
fi

if grep "mailhub=mail" "/etc/ssmtp/ssmtp.conf"; then
    echo "* configure ssmtp"
    sed -i \
        -e "s#mailhub=mail#mailhub=${MAILHUB:-localhost}#" \
        -e "s#\#FromLineOverride=YES#FromLineOverride=YES${MAILHUB:-localhost}#" \
        /etc/ssmtp/ssmtp.conf
fi

# update .env
PIMCORE_ENVIRONMENT=${PIMCORE_ENVIRONMENT:-dev}
if [ "$PIMCORE_ENVIRONMENT" = "dev" ]; then
    sed -i \
        -e "/^APP_ENV=/c\APP_ENV=dev" \
        -e "/^APP_DEBUG=/c\APP_DEBUG=true" \
        /opt/pimcore/.env
fi

if [ "$PIMCORE_ENVIRONMENT" = "prod" ]; then
    sed -i \
        -e "/^APP_ENV=/c\APP_ENV=prod" \
        -e "/^APP_DEBUG=/c\APP_DEBUG=false" \
        /opt/pimcore/.env
fi

# make sure that default bundles exist
cd /opt/pimcore/public/bundles
ln -fs ../../vendor/pimcore/pimcore/bundles/CoreBundle/Resources/public/ pimcorecore
ln -fs ../../vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/ pimcoreadmin
ln -fs ../../vendor/friendsofsymfony/jsrouting-bundle/Resources/public/ fosjsrouting

# make sure permissions are right
[ -d "/opt/pimcore/var" ] && chown www-data:www-data -R /opt/pimcore/var
[ -d "/var/lib/php/sessions" ] && chown www-data:www-data -R /var/lib/php/sessions
[ -d "/opt/pimcore/public/var" ] && chown www-data:www-data -R /opt/pimcore/public/var
