#!/command/with-contenv sh

cd /opt/pimcore
exec s6-setuidgid www-data php bin/console messenger:consume $PIMCORE_MESSENGER_DEBUG pimcore_core pimcore_scheduled_tasks pimcore_image_optimize --memory-limit=1024M --time-limit=3600
